[template]
src = "production.tmpl"
dest = "public/env-config.js"
keys = [
  "/configuration/mapServer/url",
  "/configuration/mapServer/publishPoint",
  "/configuration/mapServer/channel",
  "/configuration/mapServer/version",
  "/configuration/mapServer/request",
  "/configuration/service/protocol",
  "/configuration/service/url",
  "/configuration/activeLayer",
  "/configuration/logger/http/host",
  "/configuration/logger/http/port",
  "/configuration/logger/http/path",
  "/configuration/logger/level"
]
