 [template]
src = "production.tmpl"
dest = "src/common/config/index.ts"
keys = [
    "/configuration/mapServer/url",
    "/configuration/mapServer/publishPoint",
    "/configuration/mapServer/channel",
    "/configuration/mapServer/version",
    "/configuration/mapServer/request",
    "/configuration/service/protocol",
    "/configuration/service/url",
    "/configuration/activeLayer"
]
