[template]
src = "production.tmpl"
dest = "public/env-config.js"
keys = [
  "/configuration/ui/language",
  "/configuration/mapserver/url",
  "/configuration/mapserver/publish/point",
  "/configuration/mapserver/channel",
  "/configuration/mapserver/version",
  "/configuration/mapserver/request",
  "/configuration/service/protocol",
  "/configuration/service/url",
  "/configuration/active/layer",
  "/configuration/active/layer/properties/mapurlpath",
  "/configuration/active/layer/properties/exportpath",
  "/configuration/active/layer/properties/url/pattern",
  "/configuration/active/layer/properties/url/pattern/params/service",
  "/configuration/active/layer/properties/url/pattern/params/layers",
  "/configuration/active/layer/properties/url/pattern/params/tiled",
  "/configuration/active/layer/properties/url/pattern/params/matrixset",
  "/configuration/active/layer/properties/url/pattern/params/style",
  "/configuration/active/layer/properties/url/pattern/params/projection",
  "/configuration/map/center",
  "/configuration/map/zoom",
  "/configuration/export/default/zoom/level",
  "/configuration/export/max/zoom/level",
  "/configuration/export/url/pattern",
  "/configuration/logger/http/host",
  "/configuration/logger/http/port",
  "/configuration/logger/http/path",
  "/configuration/logger/level",
  "/configuration/logger/log2console",
  "/configuration/bbox/area/square/km/limit"
]
