[template]
src = "production.tmpl"
dest = "public/env-config.js"
keys = [
  "/configuration/ui/language",
  "/configuration/mapserver/url",
  "/configuration/mapserver/publish/point",
  "/configuration/mapserver/channel",
  "/configuration/mapserver/version",
  "/configuration/mapserver/request",
  "/configuration/service/protocol",
  "/configuration/service/url",
  "/configuration/active/layer",
  "/configuration/logger/http/host",
  "/configuration/logger/http/port",
  "/configuration/logger/http/path",
  "/configuration/logger/level",
  "/configuration/logger/log2console",
  "/configuration/bbox/area/square/km/limit"
]
